services:
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    volumes:
      - ${PWD}/cassandra/data:/var/lib/cassandra
    command: ["cassandra", "-f"]

  scripts:
    image: cassandra:latest
    volumes:
      - ${PWD}/cassandra/scripts:/scripts
    depends_on:
      - cassandra
